import type { Metadata } from "next";

import {
  Roboto_Flex as FontRobotoFlex,
  Roboto_Mono as FontRobotoMono,
  Inter as FontSans,
  Sora as FontSora,
} from "next/font/google";

import "./globals.css";
import { cn } from "@/lib/utils";

import { Footer } from "./_components/footer";
import { Header } from "./_components/header";
import { ThemeProvider } from "./_components/theme-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSora = FontSora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["700", "800"],
});

const fontRobotoMono = FontRobotoMono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  weight: ["400", "500", "700"],
});

const fontRobotoFlex = FontRobotoFlex({
  subsets: ["latin"],
  variable: "--font-roboto-flex",
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html
      lang="pt"
      className={`${fontSora.variable} ${fontRobotoMono.variable} ${fontRobotoFlex.variable}`}>
      <ThemeProvider attribute="class" defaultTheme="system">
        <body
          className={cn(
            "dark:bg-dark-hero-pattern bg-light-hero-pattern min-h-screen flex flex-col font-sans antialiased mx-auto",
            fontSans.variable
          )}>
          <Header />
          {children}
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
